### ISSUE TITLE
LeafEdit - Versions-TODO.

### ISSUE THREAD

**Issue by SuperSaiyajinStackZ** [Universal-Team/LeafEdit#29]
Here's the TODO List after v0.3.0 AKA the core finishing:

- [ ] v0.3.0 -> Core finishing, that means all different Issues needs to be at 100%.

- [ ] v0.4.0 -> UI Changes.

- [ ] v0.5.0 -> Mod Manager for AC:NL Mods.

- [ ] v1.0.0 -> Official stable release -- Recheck everything for the stable release.

v1.0.0 will take a while!! *A lot of things needs to be finished in the core even first!! If anyone likes to help, it's appreciated.*

**NO, THERE IS NO ETA!**
